### ISSUE TITLE
No message output

### ISSUE THREAD

**Issue by lagacy** [Austinsuyoyo/rocketchat-gitea-hook#1]
Hi, there is a small issue in the script making the webhooks not giving any message for the commits.

**Comment by Austinsuyoyo** [comment]
Is there any photo to show the bug?

**Comment by lagacy** [comment]
![image](https://user-images.githubusercontent.com/3036320/107576665-74f3ea80-6bbf-11eb-8ffe-ae9523c550a6.png)

**Comment by lagacy** [comment]
So it is only doing this on desktop, on mobile i can see the messages

**Comment by Austinsuyoyo** [comment]
I think there is a bug in gitea before,
So I delete message if commit length == 1

Now it will show like this
![image](https://user-images.githubusercontent.com/15572804/107607988-a4652e80-6c75-11eb-90ca-5087ed4951ab.png)

you can see what I fix in js file
[go here](https://github.com/Austinsuyoyo/rocketchat-gitea-hook/commit/5e5be68f67c04be2cf11087a0887b874d453a97c)
