### ISSUE TITLE
Blank Page when uncolapsing Commits in Rocket-Chat Since Version 4.x

### ISSUE THREAD

**Issue by icerootsvw** [Austinsuyoyo/rocketchat-gitea-hook#3]
We were using this script in the past with rocket chat 3.x very successful and like it a lot. We now updated to Rocket Chat 4 and since then we are facing the issue that when a new message is displayed in rocket chat, we can not uncolapse the view. We are just hitting an empty page then

![image](https://user-images.githubusercontent.com/40857785/155670086-e270d045-5f57-4ba4-85c0-ce18dc065b55.png)

After some research i found this bug https://github.com/RocketChat/Rocket.Chat/issues/23783 and when i understand it correctly a specific field which is used by this script now needs additional information.

So i am not sure if it is a bug in rocket chat itself or if it is a bug withing this gitea integration script

If additonal information are useful please just give me an info (and how to provide them)

**Comment by icerootsvw** [comment]
@Austinsuyoyo i wass trying to figure out where to put a title but i am lost to be honest. Do you have any idea where to put it?

**Comment by Austinsuyoyo** [comment]
> @Austinsuyoyo i wass trying to figure out where to put a title but i am lost to be honest. Do you have any idea where to put it?

I'll tried to figure it out today, but i need to setup all server first.
I'm not sure it's bug or not, maybe I can reduce some information let's webhook work

**Comment by Austinsuyoyo** [comment]
@icerootsvw  I update the script, can you tried this [one ](https://raw.githubusercontent.com/Austinsuyoyo/rocketchat-gitea-hook/master/gitea-rocketchat.hooks.js)?
If that ok please let me know, thanks ^^

**Comment by icerootsvw** [comment]
@Austinsuyoyo thank you very much, that fixed the issue and it is now possible again to uncolaps the entries.
